### ISSUE TITLE
How can we specify extras?

### ISSUE THREAD

**Issue by felipesanches** [f-actions/font-bakery#165]
For instance, this check requires fontbakery to be installed with the freetype extra:
![Screenshot from 2022-11-04 11-19-07](https://user-images.githubusercontent.com/213676/199960741-a364ec61-73e1-4760-9084-540062109e4e.png)

**Comment by chrissimpkins** [comment]
Good question.  I didn't realize that there are extras dependencies.  

The fontbakery installation options are defined @ https://github.com/f-actions/font-bakery/blob/6f923d89322362001cedb23f9032a66432274ffb/src/index.js#L24-L35

We could add an extras field to the configuration file that is empty by default and installs with extras if the configuring user defines it in the GH Action yaml configuration for their workflow run?

See https://github.com/f-actions/font-bakery/blob/6f923d89322362001cedb23f9032a66432274ffb/src/index.js#L6-L9 for how the configuration data is parsed into JS variables.

See this file for the approach to define the configuration options in this custom GH Action.

Those should be the pieces of the puzzle.
