### ISSUE TITLE
Consider installing `fonttools[interpolatable]` to improve performance of `com.google.fonts/check/interpolation_issues`

### ISSUE THREAD

**Issue by RickyDaMa** [f-actions/font-bakery#220]
A relatively recent Fontbakery check `com.google.fonts/check/interpolation_issues` is well known to be quite time-consuming and intensive to run.

One lesser documented strategy to speed it up is to install `fonttools[interpolatable]`, which pulls in some additional dependencies (`numpy` and `scipy` among them) and significantly increases how fast tests are to run.

The main Fontbakery repo - to my knowledge - doesn't want to enable these dependencies either by default or under a feature of Fontbakery, due to dependency bloat.

However, for a GitHub action, downloading the extra dependencies is cheap. Pipelines often have caches to make downloading & installing dependencies as fast as possible (`actions/setup-python` even has opt-in caching out of the box). All of this reduces the wasted cost if this test is not being run under the user's Fontbakery configuration. But then, if `com.google.fonts/check/interpolation_issues` is one of the checks being run, the extra dependencies will nearly always save on run time, directly saving CI cost

As an example, on an internal variable font project with numerous axes, we saw this single test go from ~35 minutes execution time down to ~5 minutes

All this is to say, would you consider a PR to install `fonttools[interpolatable]` alongside `fontbakery[all]` to improve performance here?

**Comment by chrissimpkins** [comment]
Yes, definitely willing to take a PR to support that. Thanks!
